### ISSUE TITLE
Other Print Format than "Standard"

### ISSUE THREAD

**Issue by DrZoidberg09** [phamos-eu/nextcloud-integration#4]
First of all great app! Thanks for the effort.

I am just setting it up for our ERPNext instance. Genereally it works super nice, but we have custom print formats. However, the app does not allow using other print formats.

I guess, there should not be an issue if other print formats are used? Would be really great if that could be integrated into the app!

**Comment by wojosc** [comment]
Hi @DrZoidberg09 thanks for using the app.

I have not understood where the Print Formats are used? I'ts best you send some screenshots to help us understand this.

**Comment by DrZoidberg09** [comment]
![Unbenannt](https://user-images.githubusercontent.com/96449693/164203591-27f1e3eb-6312-4d6a-b867-46b96a187281.PNG)

I need to define the print format which is used to generate the PDF that is then stored in the nextcloud. However, I would really like to use my custom print format instead of the standard one. But as you can see, it does not allow to select anything but the standard format.

I would guess that there should not be any technical reasons for this? Would be super nice, if that was possible.

**Comment by wojosc** [comment]
@DrZoidberg09  https://doku.phamos.eu/books/erpnext-benutzerhandbuch/page/standarddruckformat

**Comment by DrZoidberg09** [comment]
@wojosc 
Thanks for the link! That is actually pretty handy when I want to print something manually. However, if I want to generate a PDF based on my custom print format that does not help - unfortunately.
It still uses the "Standard" Print format when the PDF is generated and uploaded to Nextcloud. 
As you can see in the screenshot the print format needs to be selected for each DocType in the Nextcloud Print List and it seems to block anything but the standard print format. Again thank you so much for your help! 
The app is really nice and this function is the last piece that is missing before it can be used in production environment.

**Comment by DrZoidberg09** [comment]
I actually found the issue. In the file "[nextcloud_print_list.json](https://github.com/phamos-eu/nextcloud-integration/blob/main/nextcloud_integration/nextcloud_integration/doctype/nextcloud_print_list/nextcloud_print_list.json)" the option "Standard" needs to be removed. Then any Print Format can be selected. Actually a very simple fix. Would you mind changing this?

**Comment by wojosc** [comment]
Hi @DrZoidberg09 I have pushed the change. Please updates and see if it works. Thank you.

**Comment by DrZoidberg09** [comment]
Sorry for the late response. I could finally test it again. It now works very well. Thanks alot!

**Comment by wojosc** [comment]
thank you @DrZoidberg09
